/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ktor_simple_web

import io.ktor.server.engine.embeddedServer
import io.ktor.server.netty.Netty


class App {
    val greeting: String
        get() {
            return "Hello world."
        }
}

fun main(args: Array<String>) {

    embeddedServer(Netty, port = 8080){}.start(wait=true)


}
